### ISSUE TITLE
Clicking a patient of first screen of ward round should start ward round on that patient

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-wardround#13]
When you open any of the ward rounds it gives you a list of all the patients for the ward round.
If you click one of them it opens that specific episode in a new tab rather than starting the ward round on that patient which I think would be the expected behaviour.
Thoughts?

**Comment by davidmiller** [comment]
What I've deployed to elcid-opat is: 

* If no filters, jump straight in to first patient
* Clicking in the table takes you to that patient in the ward round you're viewing.

**Comment by michaeledwardmarks** [comment]
Perfect.

**Comment by GabPoll** [comment]
Very nice David, thank you.
