### ISSUE TITLE
As a User I would like to quickly find patients on a large ward round

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal-wardround#14]
e.g. Micro Haem has > 150 patients regularly.

Having a filter for the list similar to the list filters would be super helpful.

**Comment by davidmiller** [comment]
Closed by the "Find patient" feature - this got duplicated as an elCID issue !

**Comment by GabPoll** [comment]
i like this feature, thank you!

**Comment by davidmiller** [comment]
:) You're welcome !
