### ISSUE TITLE
No Next  Button when looking at last patient on a Ward Round

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-wardround#16]
- [ ] On last person (e.g episode N/N) the next button should be replaced by an end of ward round button.

**Comment by GabPoll** [comment]
In a different colour

**Comment by davidmiller** [comment]
What do you imagine that button does when you press it ?

**Comment by michaeledwardmarks** [comment]
Well either
- button takes you back to Ward Round screen

or

Just remove the NEXT button

**Comment by davidmiller** [comment]
NEXT button is already gone ! :)

You can get to the Ward Round screen from the top level menu.

I'm going to close this - we can always look at the ward round controls after further user research...

**Comment by michaeledwardmarks** [comment]
Agree!
